version: "3.8"

services:
    web:
        build: ./services/web
        depends_on:
            - database
        volumes:
            - ./services/web/:/src
        networks:
            - backend
        ports:
            - "8000:8000"
        env_file: app.env

    database:
        image: postgres
        volumes:
            - postgres:/var/lib/postgresql/data/
        networks:
            - backend
        ports:
            - "5432:5432"
        env_file: database.env


networks:
    backend:
        driver: bridge

volumes:
    postgres:
        driver: local
