from enum import Enum, unique


@unique
class OrderStatusEnum(Enum):
    WAITING_FOR_CONFIRMATION = "WAITING_FOR_CONFIRMATION"
    PENDING_PAYMENT = "PENDING_PAYMENT"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    PROCESSING = "PROCESSING"
    SHIPPED = "SHIPPED"
    CANCELED = "CANCELED"
    FAILED_BY_VENDOR = "FAILED_BY_VENDOR"
    UNFULFILLABLE = "UNFULFILLABLE"

@unique
class ShippingSpeedEnum(Enum):
    STANDARD = "STANDARD"
    EXPEDITED = "EXPEDITED"
    PRIORITY = "PRIORITY"
