from .address import CRUDAddress
from .admin import CRUDAdmin
from .amazonProduct import CRUDAmazonProduct
from .base import CRUDBase
from .errata import CRUDErrata
from .order import CRUDOrder
from .payment import CRUDPayment
from .product import CRUDProduct
from .recommended import CRUDRecommended
from .shipbobProduct import CRUDShipbobProduct
from .slide import CRUDSlide
